services:
  db:
    image: postgres:13
    restart: always
    volumes:
        - ./tmp/db:/var/lib/postgresql/data
    container_name: shortlink-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortlink
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shortlink"]
      interval: 5s
      timeout: 5s
      retries: 5
